/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClienteCad.java
 *
 * Created on 12/10/2009, 18:34:47
 */
package br.com.best.slbg.ui;

import br.com.best.slbg.bean.Cliente;
import br.com.best.slbg.bo.ClienteBO;
import br.com.best.slbg.util.Utilitario;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author marcelo
 */
public class ClienteCad extends javax.swing.JInternalFrame {

    private ClienteBO clienteBO;
    private Cliente cliente;

    /** Creates new form ClienteCad */
    @SuppressWarnings("static-access")
    public ClienteCad() {
        initComponents();
        this.clienteBO = new ClienteBO();
        this.cliente = new Cliente();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgModalidade = new javax.swing.ButtonGroup();
        jlCodigo = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jrbVenda = new javax.swing.JRadioButton();
        jrbAluguel = new javax.swing.JRadioButton();
        jrbLivre = new javax.swing.JRadioButton();
        jrbDemo = new javax.swing.JRadioButton();
        jlNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jlContato = new javax.swing.JLabel();
        jtfContato = new javax.swing.JTextField();
        jlCpfCnpj = new javax.swing.JLabel();
        jtfCpfCnpj = new javax.swing.JTextField();
        jlRgIe = new javax.swing.JLabel();
        jtfRgIe = new javax.swing.JTextField();
        jlDataCompra = new javax.swing.JLabel();
        jxDataCompra = new org.jdesktop.swingx.JXDatePicker();
        jlFone = new javax.swing.JLabel();
        jtfFone = new javax.swing.JTextField();
        jlEmail = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jbApagar = new javax.swing.JButton();
        jbPesquisar = new javax.swing.JButton();
        jbLiberaLicenca = new javax.swing.JButton();
        jbNovo = new javax.swing.JButton();
        jbListaLicenca = new javax.swing.JButton();
        jlQtdMaquinas = new javax.swing.JLabel();
        jsQtdMaquinas = new javax.swing.JSpinner();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Clientes");
        setMinimumSize(new java.awt.Dimension(100, 31));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jlCodigo.setText("Número do Contrato");

        jtfCodigo.setColumns(20);
        jtfCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCodigoFocusLost(evt);
            }
        });
        jtfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCodigoKeyReleased(evt);
            }
        });

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Modalidade de Venda"));

        bgModalidade.add(jrbVenda);
        jrbVenda.setSelected(true);
        jrbVenda.setText("Venda");
        jrbVenda.setBounds(10, 20, 70, 21);
        jLayeredPane1.add(jrbVenda, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bgModalidade.add(jrbAluguel);
        jrbAluguel.setText("Aluguel");
        jrbAluguel.setBounds(10, 40, 80, 20);
        jLayeredPane1.add(jrbAluguel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bgModalidade.add(jrbLivre);
        jrbLivre.setText("Livre");
        jrbLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbLivreActionPerformed(evt);
            }
        });
        jrbLivre.setBounds(170, 20, 70, 23);
        jLayeredPane1.add(jrbLivre, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bgModalidade.add(jrbDemo);
        jrbDemo.setText("Demo");
        jrbDemo.setBounds(170, 40, 80, 23);
        jLayeredPane1.add(jrbDemo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jlNome.setText("Nome / Razão Social");

        jtfNome.setColumns(40);
        jtfNome.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jtfNomeInputMethodTextChanged(evt);
            }
        });
        jtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNomeKeyReleased(evt);
            }
        });

        jlContato.setText("Contato");

        jtfContato.setColumns(40);
        jtfContato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfContatoKeyReleased(evt);
            }
        });

        jlCpfCnpj.setText("CPF /CNPJ");

        jtfCpfCnpj.setColumns(14);

        jlRgIe.setText("RG /IE");

        jtfRgIe.setColumns(14);

        jlDataCompra.setText("Data da Compra");

        jxDataCompra.setFormats(new String [] { "dd/MM/yyyy" });

        jlFone.setText("Telefone de Contato");

        jtfFone.setColumns(14);

        jlEmail.setText("E-Mail");

        jtfEmail.setColumns(30);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbApagar.setText("Apagar");
        jbApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbApagarActionPerformed(evt);
            }
        });

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jbLiberaLicenca.setText("Libera Licença");
        jbLiberaLicenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLiberaLicencaActionPerformed(evt);
            }
        });

        jbNovo.setText("Novo");
        jbNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoActionPerformed(evt);
            }
        });

        jbListaLicenca.setText("Vincular Máquinas/Licenças");
        jbListaLicenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbListaLicencaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jbNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbListaLicenca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbLiberaLicenca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbApagar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbApagar)
                    .addComponent(jbPesquisar)
                    .addComponent(jbLiberaLicenca)
                    .addComponent(jbListaLicenca)
                    .addComponent(jbNovo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlQtdMaquinas.setText("Qtd. Máquinas");

        jsQtdMaquinas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 150, 1));
        jsQtdMaquinas.setToolTipText("Quantidade de máquina que executarão o Best.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jsQtdMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlQtdMaquinas)
                    .addComponent(jtfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                    .addComponent(jlContato)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCpfCnpj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfRgIe, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlRgIe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlDataCompra)
                            .addComponent(jxDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlFone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlEmail)
                                .addGap(263, 263, 263))
                            .addComponent(jtfEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)))
                    .addComponent(jtfContato, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCodigo)
                            .addComponent(jlNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)))
                .addGap(21, 21, 21))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addComponent(jlNome)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlContato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCpfCnpj)
                    .addComponent(jlDataCompra)
                    .addComponent(jlRgIe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jxDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfRgIe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlFone)
                    .addComponent(jlEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlQtdMaquinas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsQtdMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        JInternalFrame pesquisaSerial = new PesquisaSerial();
        JDesktopPane jDesktopPane1 = Principal.getDesktop();
        jDesktopPane1.add(pesquisaSerial, 2);
        pesquisaSerial.setLocation(Principal.fy, Principal.fy);
        Principal.soma();
        pesquisaSerial.setVisible(true);
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jtfNomeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jtfNomeInputMethodTextChanged
    }//GEN-LAST:event_jtfNomeInputMethodTextChanged

    private void jtfNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyReleased
        Utilitario.transformaMaicuscula(evt);
    }//GEN-LAST:event_jtfNomeKeyReleased

    private void jbLiberaLicencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLiberaLicencaActionPerformed
        if (!jtfCodigo.getText().isEmpty()) {
            JInternalFrame liberaLicenca = new LiberaLicenca();
            JDesktopPane jDesktopPane1 = Principal.getDesktop();
            jDesktopPane1.add(liberaLicenca, 3);
            liberaLicenca.setLocation(Principal.fy, Principal.fy);
            Principal.soma();
            liberaLicenca.setVisible(true);
        }
    }//GEN-LAST:event_jbLiberaLicencaActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
    }//GEN-LAST:event_formInternalFrameActivated

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
    }//GEN-LAST:event_formFocusGained

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        if (jtfCodigo.getText().isEmpty() == false) {
            efetuaBuscaChave(jtfCodigo.getText());
        }
        jtfCodigo.requestFocusInWindow();
    }//GEN-LAST:event_formInternalFrameOpened

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if (jtfCodigo.getText().isEmpty() == false) {
            efetuaBuscaChave(jtfCodigo.getText());
        }
        jtfCodigo.requestFocusInWindow();
    }//GEN-LAST:event_formMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
    }//GEN-LAST:event_formComponentShown

    private void jbNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoActionPerformed
        limpaCampos();
        jtfCodigo.requestFocusInWindow();
    }//GEN-LAST:event_jbNovoActionPerformed

    private void jtfContatoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfContatoKeyReleased
        Utilitario.transformaMaicuscula(evt);
    }//GEN-LAST:event_jtfContatoKeyReleased

    private void jbApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbApagarActionPerformed

        Object[] options = {"Sim", "Não"};
        int escolha = JOptionPane.showOptionDialog(null, "Confirma a Exclusão do Contrato ? ", "Atenção",
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);

        if (escolha == 0) {
            // Preencher os VOs
            cliente.setRazaoSocial(jtfNome.getText());
            cliente.setNomeContato(jtfContato.getText());
            cliente.setRgIe(jtfRgIe.getText());
            cliente.setCpfCnpj(jtfCpfCnpj.getText());
            cliente.setDataVenda(jxDataCompra.getDate());
            cliente.setFone(jtfFone.getText());
            cliente.setEmail(jtfEmail.getText());

            if (jrbAluguel.isSelected()) {
                cliente.setModalidadeVenda("A");
            }

            if (jrbVenda.isSelected()) {
                cliente.setModalidadeVenda("V");
            }

            if (jrbLivre.isSelected()) {
                cliente.setModalidadeVenda("L");
            }

            if (jrbDemo.isSelected()) {
                cliente.setModalidadeVenda("D");
            }

            clienteBO.excluirCliente(cliente);
        }
        limpaCampos();
        jtfCodigo.requestFocusInWindow();
    }//GEN-LAST:event_jbApagarActionPerformed

    private void jrbLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbLivreActionPerformed
    }//GEN-LAST:event_jrbLivreActionPerformed

    private void jbListaLicencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbListaLicencaActionPerformed
        // Preencher os VOs
        if (!jtfCodigo.getText().isEmpty()) {

            Cliente clienteBest = new Cliente();

            clienteBest.setRazaoSocial(jtfNome.getText());
            clienteBest.setNomeContato(jtfContato.getText());
            clienteBest.setRgIe(jtfRgIe.getText());
            clienteBest.setCpfCnpj(jtfCpfCnpj.getText());
            clienteBest.setDataVenda(jxDataCompra.getDate());
            clienteBest.setFone(jtfFone.getText());
            clienteBest.setEmail(jtfEmail.getText());
            clienteBest.setQtdMaquinas((Integer) jsQtdMaquinas.getValue());

            if (jrbAluguel.isSelected()) {
                clienteBest.setModalidadeVenda("A");
            }

            if (jrbVenda.isSelected()) {
                clienteBest.setModalidadeVenda("V");
            }

            if (jrbLivre.isSelected()) {
                clienteBest.setModalidadeVenda("L");
            }

            if (jrbDemo.isSelected()) {
                clienteBest.setModalidadeVenda("D");
            }

            if (!jtfCodigo.getText().isEmpty()) {
                clienteBest.setNumeroContrato(jtfCodigo.getText());
            }

            JInternalFrame relacaoLicenca = new RelacaoLicencas(clienteBest);
            JDesktopPane jDesktopPane1 = Principal.getDesktop();
            jDesktopPane1.add(relacaoLicenca, 5);
            relacaoLicenca.setLocation(Principal.fy, Principal.fy);
            Principal.soma();

            relacaoLicenca.setVisible(true);
        }
    }//GEN-LAST:event_jbListaLicencaActionPerformed

    private void jtfCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoKeyReleased
        Utilitario.transformaMaicuscula(evt);
    }//GEN-LAST:event_jtfCodigoKeyReleased

    private void jtfCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCodigoFocusLost
        if (!jtfCodigo.getText().isEmpty()) {
            cliente = clienteBO.consultaClientesId(jtfCodigo.getText());
            cargaComponente(cliente);
        }
    }//GEN-LAST:event_jtfCodigoFocusLost
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgModalidade;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbApagar;
    private javax.swing.JButton jbLiberaLicenca;
    private javax.swing.JButton jbListaLicenca;
    private javax.swing.JButton jbNovo;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlContato;
    private javax.swing.JLabel jlCpfCnpj;
    private javax.swing.JLabel jlDataCompra;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlFone;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlQtdMaquinas;
    private javax.swing.JLabel jlRgIe;
    private javax.swing.JRadioButton jrbAluguel;
    private javax.swing.JRadioButton jrbDemo;
    private javax.swing.JRadioButton jrbLivre;
    private javax.swing.JRadioButton jrbVenda;
    public static javax.swing.JSpinner jsQtdMaquinas;
    public static javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfContato;
    private javax.swing.JTextField jtfCpfCnpj;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfFone;
    public static javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfRgIe;
    private org.jdesktop.swingx.JXDatePicker jxDataCompra;
    // End of variables declaration//GEN-END:variables

    public void limpaCampos() {
        jtfCodigo.setText("");
        jtfNome.setText("");
        jtfContato.setText("");
        jtfRgIe.setText("");
        jtfEmail.setText("");
        jtfFone.setText("");
        jtfCpfCnpj.setText("");
        jsQtdMaquinas.setValue(1);
        jrbVenda.setSelected(true);
    }

    public void efetuaBuscaChave(String codigo) {
        if (codigo.length() > 5) {
            cliente = clienteBO.consultaClientesId(codigo);
            cargaComponente(cliente);
        }
    }

    public String buscaUltimaChave() {
        return clienteBO.QtdMaxLinhas().toString();
    }

    public void cargaComponente(Cliente cliente) {
        if (!cliente.getNumeroContrato().isEmpty()) {
            jtfContato.setText(cliente.getNomeContato());
            jtfRgIe.setText(cliente.getRgIe());
            jtfEmail.setText(cliente.getEmail());
            jtfFone.setText(cliente.getFone());
            jtfNome.setText(cliente.getRazaoSocial());
            jtfCpfCnpj.setText(cliente.getCpfCnpj());
            jxDataCompra.setDate(cliente.getDataVenda());
            jsQtdMaquinas.setValue(cliente.getQtdMaquinas() != null ? cliente.getQtdMaquinas() : 0);

            if (cliente.getModalidadeVenda().equalsIgnoreCase("V")) {
                jrbVenda.setSelected(true);
            }

            if (cliente.getModalidadeVenda().equalsIgnoreCase("A")) {
                jrbAluguel.setSelected(true);
            }

            if (cliente.getModalidadeVenda().equalsIgnoreCase("D")) {
                jrbDemo.setSelected(true);
            }

            if (cliente.getModalidadeVenda().equalsIgnoreCase("L")) {
                jrbLivre.setSelected(true);
            }
        }

    }
}
