/*
 * LiberaLicenca.java
 *
 * Created on 13/10/2009, 10:47:50
 */
package br.com.best.slbg.ui;

import br.com.best.slbg.bean.Licenca;
import br.com.best.slbg.bean.LicencaPK;
import br.com.best.slbg.bo.ClienteBO;
import br.com.best.slbg.util.Utilitario;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;

/**
 *
 * @author marcelo
 */
public class LiberaLicenca extends javax.swing.JInternalFrame {

    private Utilitario utilitario;
    private ClienteBO clienteBO;
    private Licenca licenca;
    private LicencaPK licencaPK;
    private Vector<Licenca> listaMaquinas = new Vector<Licenca>();

    /** Creates new form LiberaLicenca */
    public LiberaLicenca() {
        initComponents();
        this.utilitario = new Utilitario();
        this.clienteBO = new ClienteBO();
        this.licencaPK = new LicencaPK();
        this.licenca = new Licenca();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbEfetiva = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jlNomeMaquina = new javax.swing.JLabel();
        jtfNomeMaquina = new javax.swing.JTextField();
        jlValorBest = new javax.swing.JLabel();
        jtfValorGeradoBest = new javax.swing.JTextField();
        jlSerial = new javax.swing.JLabel();
        jtfSerial = new javax.swing.JTextField();
        jlDataProximoValidacao = new javax.swing.JLabel();
        jftfDataValidacao = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtLicenca = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Liberação do Best");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbEfetiva.setText("Efetiva Liberação do Serial");
        jbEfetiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEfetivaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(598, Short.MAX_VALUE)
                .addComponent(jbEfetiva)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbEfetiva)
                .addContainerGap())
        );

        jLabel1.setText("Número do Contrato");

        jtfCodigo.setColumns(20);
        jtfCodigo.setEditable(false);

        jLabel2.setText("Nome / Razão Social");

        jtfNome.setColumns(60);
        jtfNome.setEditable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlNomeMaquina.setText("Nome Máquina");

        jtfNomeMaquina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNomeMaquinaKeyReleased(evt);
            }
        });

        jlValorBest.setText("Valor Gerado Best");

        jtfValorGeradoBest.setColumns(20);
        jtfValorGeradoBest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfValorGeradoBestFocusLost(evt);
            }
        });
        jtfValorGeradoBest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfValorGeradoBestKeyReleased(evt);
            }
        });

        jlSerial.setText("Serial");

        jtfSerial.setColumns(100);
        jtfSerial.setEditable(false);

        jlDataProximoValidacao.setText("Data Próxima Validação");

        jftfDataValidacao.setColumns(10);
        jftfDataValidacao.setEditable(false);
        jftfDataValidacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfSerial, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                    .addComponent(jlSerial)
                    .addComponent(jlNomeMaquina)
                    .addComponent(jtfNomeMaquina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfValorGeradoBest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlValorBest)
                    .addComponent(jlDataProximoValidacao)
                    .addComponent(jftfDataValidacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(222, 222, 222))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValorBest)
                    .addComponent(jlNomeMaquina))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfValorGeradoBest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNomeMaquina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlSerial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfSerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlDataProximoValidacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jftfDataValidacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtLicenca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome Servidor", "Nome Máquina", "Qtd. Modeler", "Qtd. Viewer", "Valor Gerado Best", "Serial"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtLicenca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtLicencaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtLicenca);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // Captar os dados do Form chamador
        jtfCodigo.setText(ClienteCad.jtfCodigo.getText());
        jtfNome.setText(ClienteCad.jtfNome.getText());

        // Preencher o jTable
        listaMaquinas =
                clienteBO.consultaLicencasPorContrato(jtfCodigo.getText());
        if (!listaMaquinas.isEmpty()) {
            // Obtem o modelo da JTable
            DefaultTableModel modelo = utilitario.retornaModeloTabela(jtLicenca);

            // Efetua a carga das informações vindas do banco para a
            // Grid
            for (Licenca licencas : listaMaquinas) {
                Vector<Object> colunas = new Vector<Object>();
                colunas.add(licencas.getLicencaPK().getNomeServidor());
                colunas.add(licencas.getNomeMaquina());
                colunas.add(licencas.getQtdModelo());
                colunas.add(licencas.getQtdVisao());
                colunas.add(licencas.getValorGeradoBest());
                colunas.add(licencas.getValorSerial());

                modelo.addRow(colunas);
            }
        }
    }//GEN-LAST:event_formInternalFrameActivated

    private void jtLicencaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtLicencaMouseClicked
        // Aqui devo mudar os dados abaixo da JTable, conforme a linha
        // escolhida

        // Obtenho a linha clicada pelo usuário no jTable
        int linha = utilitario.retornaLinhaTabela(jtLicenca);

        // Carrego os dados da entidade Licenca no objeto 'licenca'
        licenca = listaMaquinas.get(linha);
        licencaPK.setNomeServidor(licenca.getLicencaPK().getNomeServidor());
        licencaPK.setNumeroContrato(licenca.getLicencaPK().getNumeroContrato());

        // Seto os dados da tela
        jtfValorGeradoBest.setText(licenca.getValorGeradoBest());
        jtfSerial.setText(licenca.getValorSerial());
    }//GEN-LAST:event_jtLicencaMouseClicked

    private void jbEfetivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEfetivaActionPerformed
        Object[] options = {"Sim", "Não"};
        int escolha = JOptionPane.showOptionDialog(null, "Confirma a Liberação do Número Serial ?", "Atenção",
                JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);

        if (escolha == 0) {
            licenca.setValorGeradoBest(jtfValorGeradoBest.getText());
            licenca.setNomeMaquina(jtfNomeMaquina.getText());
            clienteBO.incluirRelacaoLicencas(licenca);
        }
        this.dispose();

    }//GEN-LAST:event_jbEfetivaActionPerformed

    private void jtfValorGeradoBestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfValorGeradoBestFocusLost
        // Gerar os Números Seriais
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        if (!jtfValorGeradoBest.getText().isEmpty()) {
            jtfSerial.setText(clienteBO.geraSerial(
                    clienteBO.consultaClientesId(licenca.getLicencaPK().getNumeroContrato()),
                    licenca, jtfValorGeradoBest.getText()));
        }
        licenca.setValorSerial(jtfSerial.getText());

        if (licenca.getDataProximaRenovacaoAluguel() != null) {
            jftfDataValidacao.setText(sdf.format(licenca.getDataProximaRenovacaoAluguel()).toString());
        }
        licenca.setValorGeradoBest(clienteBO.retornaSerialDisco(jtfValorGeradoBest.getText()));
    }//GEN-LAST:event_jtfValorGeradoBestFocusLost

    private void jtfValorGeradoBestKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfValorGeradoBestKeyReleased
        Utilitario.transformaMaicuscula(evt);
    }//GEN-LAST:event_jtfValorGeradoBestKeyReleased

    private void jtfNomeMaquinaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeMaquinaKeyReleased
        Utilitario.transformaMaicuscula(evt);
    }//GEN-LAST:event_jtfNomeMaquinaKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEfetiva;
    private javax.swing.JFormattedTextField jftfDataValidacao;
    private javax.swing.JLabel jlDataProximoValidacao;
    private javax.swing.JLabel jlNomeMaquina;
    private javax.swing.JLabel jlSerial;
    private javax.swing.JLabel jlValorBest;
    private javax.swing.JTable jtLicenca;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNomeMaquina;
    private javax.swing.JTextField jtfSerial;
    private javax.swing.JTextField jtfValorGeradoBest;
    // End of variables declaration//GEN-END:variables
}
