/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal.java
 *
 * Created on 12/10/2009, 16:34:32
 */
package br.com.best.slbg.ui;

import com.jgoodies.looks.plastic.Plastic3DLookAndFeel;
import java.awt.AWTKeyStroke;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.util.HashSet;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author marcelo
 */
public class Principal extends javax.swing.JFrame {

    /** Creates new form Principal */
    public Principal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbToolBar = new javax.swing.JToolBar();
        jbCliente = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jbBestNg = new javax.swing.JButton();
        jbSobre = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jbSaida = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jmbPrincipal = new javax.swing.JMenuBar();
        jmCadastro = new javax.swing.JMenu();
        jmiCliente = new javax.swing.JMenuItem();
        jmiConsultaVencimento = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jmiSair = new javax.swing.JMenuItem();
        jmVisual = new javax.swing.JMenu();
        jmiMetal = new javax.swing.JMenuItem();
        jmiMotif = new javax.swing.JMenuItem();
        jmiWindows = new javax.swing.JMenuItem();
        jmiWindowsClassico = new javax.swing.JMenuItem();
        jmAjuda = new javax.swing.JMenu();
        jmiBestNG = new javax.swing.JMenuItem();
        jmiSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Serial Licence Best Generator");
        setIconImage(new ImageIcon(getClass()
            .getResource("/br/com/best/slbg/imagens/BestL.gif")).getImage());
    addWindowListener(new java.awt.event.WindowAdapter() {
        public void windowOpened(java.awt.event.WindowEvent evt) {
            formWindowOpened(evt);
        }
    });

    jtbToolBar.setRollover(true);

    jbCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/best/slbg/imagens/document_a4_add.png"))); // NOI18N
    jbCliente.setFocusable(false);
    jbCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jbCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jbCliente.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbClienteActionPerformed(evt);
        }
    });
    jtbToolBar.add(jbCliente);
    jtbToolBar.add(jSeparator2);

    jbBestNg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/best/slbg/imagens/icon_wand.gif"))); // NOI18N
    jbBestNg.setFocusable(false);
    jbBestNg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jbBestNg.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jtbToolBar.add(jbBestNg);

    jbSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/best/slbg/imagens/fav_pressi.gif"))); // NOI18N
    jbSobre.setFocusable(false);
    jbSobre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jbSobre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jbSobre.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbSobreActionPerformed(evt);
        }
    });
    jtbToolBar.add(jbSobre);
    jtbToolBar.add(jSeparator3);

    jbSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/best/slbg/imagens/action_stop.gif"))); // NOI18N
    jbSaida.setFocusable(false);
    jbSaida.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jbSaida.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jbSaida.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jbSaidaActionPerformed(evt);
        }
    });
    jtbToolBar.add(jbSaida);

    jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 708, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 23, Short.MAX_VALUE)
    );

    jmCadastro.setText("Manutenção");

    jmiCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/best/slbg/imagens/document_a4_add.png"))); // NOI18N
    jmiCliente.setText("Cliente");
    jmiCliente.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jmiClienteActionPerformed(evt);
        }
    });
    jmCadastro.add(jmiCliente);

    jmiConsultaVencimento.setText("Consulta Vencimentos Licença");
    jmiConsultaVencimento.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jmiConsultaVencimentoActionPerformed(evt);
        }
    });
    jmCadastro.add(jmiConsultaVencimento);
    jmCadastro.add(jSeparator1);

    jmiSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
    jmiSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/best/slbg/imagens/action_stop.gif"))); // NOI18N
    jmiSair.setText("Sair");
    jmiSair.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jmiSairActionPerformed(evt);
        }
    });
    jmCadastro.add(jmiSair);

    jmbPrincipal.add(jmCadastro);

    jmVisual.setText("Look&Feel");

    jmiMetal.setText("Metal");
    jmiMetal.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jmiMetalActionPerformed(evt);
        }
    });
    jmVisual.add(jmiMetal);

    jmiMotif.setText("Motif");
    jmiMotif.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jmiMotifActionPerformed(evt);
        }
    });
    jmVisual.add(jmiMotif);

    jmiWindows.setText("Windows");
    jmiWindows.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jmiWindowsActionPerformed(evt);
        }
    });
    jmVisual.add(jmiWindows);

    jmiWindowsClassico.setText("Windows Clássico");
    jmiWindowsClassico.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jmiWindowsClassicoActionPerformed(evt);
        }
    });
    jmVisual.add(jmiWindowsClassico);

    jmbPrincipal.add(jmVisual);

    jmAjuda.setText("Ajuda");

    jmiBestNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/best/slbg/imagens/icon_wand.gif"))); // NOI18N
    jmiBestNG.setText("BestNG");
    jmAjuda.add(jmiBestNG);

    jmiSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/best/slbg/imagens/fav_pressi.gif"))); // NOI18N
    jmiSobre.setText("Sobre");
    jmiSobre.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jmiSobreActionPerformed(evt);
        }
    });
    jmAjuda.add(jmiSobre);

    jmbPrincipal.add(jmAjuda);

    setJMenuBar(jmbPrincipal);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jtbToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jtbToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    setBounds((screenSize.width-720)/2, (screenSize.height-401)/2, 720, 401);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiSairActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Abrir o Form já maximizado
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        // Colocando enter para pular de campo
        HashSet conj = new HashSet(this.getFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS));
        conj.add(AWTKeyStroke.getAWTKeyStroke(KeyEvent.VK_ENTER, 0));
        this.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS, conj);
    }//GEN-LAST:event_formWindowOpened

    private void jmiMetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMetalActionPerformed
        this.mudaLookAndFeel(0);
    }//GEN-LAST:event_jmiMetalActionPerformed

    private void jmiMotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMotifActionPerformed
        this.mudaLookAndFeel(2);
    }//GEN-LAST:event_jmiMotifActionPerformed

    private void jmiWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiWindowsActionPerformed
        this.mudaLookAndFeel(1);
    }//GEN-LAST:event_jmiWindowsActionPerformed

    private void jmiWindowsClassicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiWindowsClassicoActionPerformed
        this.mudaLookAndFeel(3);
    }//GEN-LAST:event_jmiWindowsClassicoActionPerformed

    private void jbSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaidaActionPerformed
        jmiSairActionPerformed(evt);
    }//GEN-LAST:event_jbSaidaActionPerformed

    private void jmiClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClienteActionPerformed
        JInternalFrame cliente = new ClienteCad();
        jDesktopPane1.add(cliente, 1);
        cliente.setLocation(fy, fy);
        soma();
        cliente.setVisible(true);
    }//GEN-LAST:event_jmiClienteActionPerformed

    private void jbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClienteActionPerformed
        jmiClienteActionPerformed(evt);
    }//GEN-LAST:event_jbClienteActionPerformed

    private void jmiSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSobreActionPerformed
        JInternalFrame sobre = new SobreSLBG();
        jDesktopPane1.add(sobre, 5);
        sobre.setVisible(true);
    }//GEN-LAST:event_jmiSobreActionPerformed

    private void jbSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSobreActionPerformed
        jmiSobreActionPerformed(evt);
    }//GEN-LAST:event_jbSobreActionPerformed

    private void jmiConsultaVencimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultaVencimentoActionPerformed
        // Chama o Form de Consulta dos Vencimentos
        JInternalFrame consultaVencimento = new ConsultaVencimento();
        jDesktopPane1.add(consultaVencimento, 6);
        consultaVencimento.setLocation(fy, fy);
        soma();
        consultaVencimento.setVisible(true);

    }//GEN-LAST:event_jmiConsultaVencimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    //javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    //javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    javax.swing.UIManager.setLookAndFeel(new Plastic3DLookAndFeel());
                } catch (Exception e) {
                    System.out.println(e);
                }
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JButton jbBestNg;
    private javax.swing.JButton jbCliente;
    private javax.swing.JButton jbSaida;
    private javax.swing.JButton jbSobre;
    private javax.swing.JMenu jmAjuda;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmVisual;
    private javax.swing.JMenuBar jmbPrincipal;
    private javax.swing.JMenuItem jmiBestNG;
    private javax.swing.JMenuItem jmiCliente;
    private javax.swing.JMenuItem jmiConsultaVencimento;
    private javax.swing.JMenuItem jmiMetal;
    private javax.swing.JMenuItem jmiMotif;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiSobre;
    private javax.swing.JMenuItem jmiWindows;
    private javax.swing.JMenuItem jmiWindowsClassico;
    private javax.swing.JToolBar jtbToolBar;
    // End of variables declaration//GEN-END:variables
    public static int fy = 0;
    private javax.swing.UIManager.LookAndFeelInfo looks[];

    public static javax.swing.JDesktopPane getDesktop() {
        return jDesktopPane1;
    }

    public static int soma() {
        fy += 35;
        return fy;
    }

    public void mudaLookAndFeel(int index) {
        looks = javax.swing.UIManager.getInstalledLookAndFeels();
        try {
            javax.swing.UIManager.setLookAndFeel(looks[index].getClassName());
            javax.swing.SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
